// frontend-nuxtjs/app/pages/boards/index.vue
<script setup lang="ts">
const { user, logout } = useAuth()
const { $api } = useNuxtApp()
const toast = useToast()

const boards = ref<Board[]>([])
const loading = ref(true)
const showForm = ref(false)
const newTitle = ref('')
const error = ref('')
const deleteBoardId = ref<number | null>(null)
const deleteModalOpen = computed({
  get: () => deleteBoardId.value !== null,
  set: (v: boolean) => { if (!v) deleteBoardId.value = null }
})

const boardToDelete = computed(() =>
  boards.value.find(b => b.id === deleteBoardId.value)
)

async function fetchBoards() {
  try {
    boards.value = await $api<Board[]>('/boards')
  }
  catch {
    error.value = 'Failed to load boards'
  }
  finally {
    loading.value = false
  }
}

async function createBoard() {
  if (!newTitle.value.trim()) return
  try {
    const board = await $api<Board>('/boards', {
      method: 'POST',
      body: { title: newTitle.value.trim() }
    })
    boards.value.push(board)
    newTitle.value = ''
    showForm.value = false
  }
  catch {
    error.value = 'Failed to create board'
  }
}

async function deleteBoard() {
  if (!boardToDelete.value) return
  try {
    await $api(`/boards/${boardToDelete.value.id}`, { method: 'DELETE' })
    boards.value = boards.value.filter(b => b.id !== boardToDelete.value!.id)
    deleteBoardId.value = null
  }
  catch {
    error.value = 'Failed to delete board'
  }
}

function handleLogout() {
  logout()
  navigateTo('/', { replace: true })
}

onMounted(() => {
  fetchBoards()
})
</script>

<template>
  <div class="min-h-screen bg-background">
    <header class="flex items-center justify-between px-6 py-4 bg-elevated/50 backdrop-blur">
      <h1 class="text-xl font-bold text-primary">
        My Boards
      </h1>
      <div class="flex items-center gap-3">
        <span class="text-sm text-muted">{{ user?.username }}</span>
        <UColorModeButton />
        <UButton
          variant="ghost"
          size="sm"
          icon="i-lucide-log-out"
          @click="handleLogout"
        >
          Logout
        </UButton>
      </div>
    </header>

    <USeparator />

    <main class="p-6 min-h-[calc(100vh-65px)]">
      <UAlert
        v-if="error"
        color="error"
        icon="i-lucide-circle-x"
        :title="error"
        class="mb-4"
      />

      <div class="mb-6">
        <form
          v-if="showForm"
          class="flex gap-2"
          @submit.prevent="createBoard"
        >
          <UInput
            v-model="newTitle"
            placeholder="Board title"
            autofocus
          />
          <UButton type="submit">
            Create
          </UButton>
          <UButton
            type="button"
            variant="ghost"
            @click="showForm = false; newTitle = ''"
          >
            Cancel
          </UButton>
        </form>
        <UButton
          v-else
          icon="i-lucide-plus"
          @click="showForm = true"
        >
          New Board
        </UButton>
      </div>

      <div
        v-if="loading"
        class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
      >
        <USkeleton
          v-for="i in 4"
          :key="i"
          class="h-32 w-full"
        />
      </div>

      <UEmpty
        v-else-if="boards.length === 0"
        icon="i-lucide-folder"
        title="No boards yet"
        description="Create your first board to get started."
      >
        <UButton @click="showForm = true">
          Create Board
        </UButton>
      </UEmpty>

      <div
        v-else
        class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
      >
        <UCard
          v-for="board in boards"
          :key="board.id"
          class="group transition-all hover:shadow-lg"
        >
          <template #header>
            <h3 class="text-lg font-semibold">
              {{ board.title }}
            </h3>
            <p class="text-sm text-muted">
              Created {{ new Date(board.createdAt).toLocaleDateString() }}
            </p>
          </template>

          <template #footer>
            <div class="flex justify-between w-full">
              <UButton
                variant="ghost"
                class="flex-1 justify-start"
                @click="navigateTo(`/boards/${board.id}`)"
              >
                Open
              </UButton>
              <UButton
                variant="ghost"
                icon="i-lucide-trash"
                color="error"
                @click="deleteBoardId = board.id"
              />
            </div>
          </template>
        </UCard>
      </div>
    </main>

    <UModal v-model:open="deleteModalOpen">
      <template #header>
        <h3 class="text-lg font-semibold">
          Delete Board
        </h3>
      </template>
      <p class="text-muted">
        Are you sure you want to delete "{{ boardToDelete?.title }}"? This action cannot be undone.
      </p>
      <template #footer>
        <UButton
          variant="ghost"
          @click="deleteBoardId = null"
        >
          Cancel
        </UButton>
        <UButton
          color="error"
          @click="deleteBoard"
        >
          Delete
        </UButton>
      </template>
    </UModal>
  </div>
</template>

// frontend/src/app/boards/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { LogOutIcon, PlusIcon, FolderIcon, TrashIcon } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Alert,
  AlertDescription,
} from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty, EmptyContent, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Separator } from '@/components/ui/separator';
import { Input } from '@/components/ui/input';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';

interface Board {
  id: number;
  title: string;
  userId: number;
  createdAt: string;
  updatedAt: string;
}

export default function BoardsPage() {
  const { user, isLoading: authLoading, logout } = useAuth();
  const router = useRouter();
  const [boards, setBoards] = useState<Board[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [error, setError] = useState('');
  const [deleteBoardId, setDeleteBoardId] = useState<number | null>(null);

  const fetchBoards = useCallback(async () => {
    try {
      const data = await api.get<Board[]>('/boards');
      setBoards(data);
    } catch {
      setError('Failed to load boards');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!authLoading && !user) {
      router.replace('/');
      return;
    }
    if (user) {
      fetchBoards();
    }
  }, [user, authLoading, router, fetchBoards]);

  async function createBoard(e: React.FormEvent) {
    e.preventDefault();
    if (!newTitle.trim()) return;
    try {
      const board = await api.post<Board>('/boards', { title: newTitle.trim() });
      setBoards((prev) => [...prev, board]);
      setNewTitle('');
      setShowForm(false);
    } catch {
      setError('Failed to create board');
    }
  }

  async function deleteBoard(id: number, title: string) {
    try {
      await api.delete(`/boards/${id}`);
      setBoards((prev) => prev.filter((b) => b.id !== id));
      setDeleteBoardId(null);
    } catch {
      setError('Failed to delete board');
    }
  }

  const boardToDelete = boards.find((b) => b.id === deleteBoardId);

  if (authLoading || (!user && authLoading)) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4">
        <h1 className="text-xl font-bold">My Boards</h1>
        <div className="flex items-center gap-4">
          <span className="text-sm text-muted-foreground">{user?.username}</span>
          <Button variant="ghost" size="sm" onClick={logout}>
            <LogOutIcon data-icon="inline-start" />
            Logout
          </Button>
        </div>
      </header>

      <Separator />

      <main className="p-6">
        {error && (
          <Alert variant="destructive" className="mb-4">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* New board button / form */}
        <div className="mb-6">
          {showForm ? (
            <form onSubmit={createBoard} className="flex gap-2">
              <Input
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="Board title"
                autoFocus
              />
              <Button type="submit" size="default">
                Create
              </Button>
              <Button
                type="button"
                variant="ghost"
                onClick={() => {
                  setShowForm(false);
                  setNewTitle('');
                }}
              >
                Cancel
              </Button>
            </form>
          ) : (
            <Button onClick={() => setShowForm(true)}>
              <PlusIcon data-icon="inline-start" />
              New Board
            </Button>
          )}
        </div>

        {/* Boards grid */}
        {loading ? (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <Skeleton className="h-32 w-full" />
            <Skeleton className="h-32 w-full" />
            <Skeleton className="h-32 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
        ) : boards.length === 0 ? (
          <Empty>
            <EmptyHeader>
              <EmptyMedia variant="icon"><FolderIcon /></EmptyMedia>
              <EmptyTitle>No boards yet</EmptyTitle>
              <EmptyDescription>Create your first board to get started.</EmptyDescription>
            </EmptyHeader>
            <EmptyContent>
              <Button onClick={() => setShowForm(true)}>Create Board</Button>
            </EmptyContent>
          </Empty>
        ) : (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {boards.map((board) => (
              <Card key={board.id} className="group transition-shadow hover:shadow-lg">
                <CardHeader>
                  <CardTitle className="text-lg">{board.title}</CardTitle>
                  <CardDescription>
                    Created {new Date(board.createdAt).toLocaleDateString()}
                  </CardDescription>
                </CardHeader>
                <CardFooter className="justify-between">
                  <Button
                    variant="ghost"
                    className="flex-1 justify-start"
                    onClick={() => router.push(`/boards/${board.id}`)}
                  >
                    Open
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setDeleteBoardId(board.id)}
                  >
                    <TrashIcon data-icon="only" />
                  </Button>
                </CardFooter>
              </Card>
            ))}
          </div>
        )}
      </main>

      {/* Delete confirmation dialog */}
      {boardToDelete && (
        <AlertDialog open={deleteBoardId === boardToDelete.id} onOpenChange={(open) => !open && setDeleteBoardId(null)}>
          <AlertDialogContent size="sm">
            <AlertDialogHeader>
              <AlertDialogTitle>Delete Board</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete "{boardToDelete.title}"? This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={() => deleteBoard(boardToDelete.id, boardToDelete.title)}>
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      )}
    </div>
  );
}
