// frontend-vue/app/components/AddListForm.vue
<script setup lang="ts">
const emit = defineEmits<{
  add: [title: string]
}>()

const show = ref(false)
const title = ref('')
const submitting = ref(false)

async function handleSubmit() {
  if (!title.value.trim()) return
  submitting.value = true
  try {
    emit('add', title.value.trim())
    title.value = ''
    show.value = false
  }
  finally {
    submitting.value = false
  }
}

function cancel() {
  show.value = false
  title.value = ''
}
</script>

<template>
  <UButton
    v-if="!show"
    variant="secondary"
    icon="i-lucide-plus"
    class="h-fit shrink-0"
    @click="show = true"
  >
    Add list
  </UButton>

  <UCard
    v-else
    class="h-fit shrink-0 w-[280px] border-dashed"
  >
    <form
      class="flex flex-col gap-2"
      @submit.prevent="handleSubmit"
    >
      <UInput
        v-model="title"
        placeholder="List title"
        autofocus
      />
      <div class="flex gap-2">
        <UButton
          type="submit"
          size="sm"
          :loading="submitting"
        >
          Add
        </UButton>
        <UButton
          type="button"
          variant="ghost"
          size="sm"
          @click="cancel"
        >
          Cancel
        </UButton>
      </div>
    </form>
  </UCard>
</template>

// frontend/src/components/AddListForm.tsx
'use client';

import { useState } from 'react';
import { PlusIcon } from 'lucide-react';
import type { List as ListType, Card as CardType } from '@/lib/types';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';

interface AddListFormProps {
  onAdd: (title: string) => Promise<void>;
}

export default function AddListForm({ onAdd }: AddListFormProps) {
  const [show, setShow] = useState(false);
  const [title, setTitle] = useState('');
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setSubmitting(true);
    try {
      await onAdd(title.trim());
      setTitle('');
      setShow(false);
    } finally {
      setSubmitting(false);
    }
  }

  if (!show) {
    return (
      <Button
        variant="secondary"
        className="h-fit shrink-0"
        onClick={() => setShow(true)}
      >
        <PlusIcon data-icon="inline-start" />
        Add list
      </Button>
    );
  }

  return (
    <Card className="h-fit shrink-0 w-[280px] bg-muted">
      <CardContent className="p-3">
        <form onSubmit={handleSubmit} className="flex flex-col gap-2">
          <Input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="List title"
            autoFocus
          />
          <div className="flex gap-2">
            <Button type="submit" disabled={submitting} size="sm">
              Add
            </Button>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => {
                setShow(false);
                setTitle('');
              }}
            >
              Cancel
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
