// frontend/src/components/CardEditModal.tsx
'use client';

import { useState } from 'react';
import { XIcon } from 'lucide-react';
import type { Card } from '@/lib/types';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

interface CardEditModalProps {
  card: Card;
  onSave: (id: number, title: string, content: string | null) => Promise<void>;
  onClose: () => void;
}

export default function CardEditModal({ card, onSave, onClose }: CardEditModalProps) {
  const [title, setTitle] = useState(card.title);
  const [content, setContent] = useState(card.content || '');
  const [saving, setSaving] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setSaving(true);
    try {
      await onSave(card.id, title.trim(), content.trim() || null);
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit Card</DialogTitle>
          <DialogDescription>
            Edit the card title and description below.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <FieldGroup className="gap-4">
            <Field>
              <FieldLabel htmlFor="title">Title</FieldLabel>
              <Input
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                autoFocus
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="content">Description</FieldLabel>
              <Textarea
                id="content"
                value={content}
                onChange={(e) => setContent(e.target.value)}
                rows={4}
                placeholder="Add a description..."
              />
            </Field>
          </FieldGroup>
          <DialogFooter className="mt-4">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={saving}>
              {saving ? 'Saving...' : 'Save'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// frontend-vue/app/components/CardEditModal.vue
<script setup lang="ts">
import type { Card } from '~/types'

const props = defineProps<{
  card: Card
}>()

const emit = defineEmits<{
  save: [id: number, title: string, content: string | null]
  close: []
}>()

const title = ref(props.card.title)
const content = ref(props.card.content || '')
const saving = ref(false)

async function handleSubmit() {
  if (!title.value.trim()) return
  saving.value = true
  try {
    emit('save', props.card.id, title.value.trim(), content.value.trim() || null)
  }
  finally {
    saving.value = false
  }
}

function handleClose() {
  emit('close')
}
</script>

<template>
  <UModal :open="true" @update:open="handleClose">
    <template #header>
      <h3 class="text-lg font-semibold">
        Edit Card
      </h3>
    </template>

    <form
      class="flex flex-col gap-4"
      @submit.prevent="handleSubmit"
    >
      <UFormField label="Title" name="title">
        <UInput
          v-model="title"
          autofocus
        />
      </UFormField>

      <UFormField label="Description" name="content">
        <UTextarea
          v-model="content"
          :rows="4"
          placeholder="Add a description..."
        />
      </UFormField>
    </form>

    <template #footer>
      <UButton
        variant="ghost"
        @click="handleClose"
      >
        Cancel
      </UButton>
      <UButton
        :loading="saving"
        @click="handleSubmit"
      >
        {{ saving ? 'Saving...' : 'Save' }}
      </UButton>
    </template>
  </UModal>
</template>
